//Include this reference module in product release notes.
//Be sure you declare runtimes-attributes.doc
//Content is intended for runtimes doc projects.

[id='runtimes_metering_labels-{context}']
= {ProductName} metering labels for Red Hat OpenShift

You can add metering labels to your {ProductName} pods and check Red Hat subscription details with the OpenShift Metering Operator.

[NOTE]
====
* Do not add metering labels to any pods that an operator or a template deploys and manages.
* You can apply labels to pods using the Metering Operator on OpenShift Container Platform version 4.8 and earlier. From version 4.9 onward, the Metering Operator is no longer available without a direct replacement.
====

{ProductName} can use the following metering labels:

* `com.company: Red_Hat`
* `rht.prod_name: {product-name}`
* `rht.prod_ver: {product-version}`
* `rht.comp: {component-name}`
* `rht.comp_ver: {component-version}`
* `rht.subcomp: {sub-component-name}`
* `rht.subcomp_t: {component-type}`

[role="_additional-resources"]
.Additional resources
* link:{metering-doc-root}[Configuring and using Metering in OpenShift Container Platform]
