// Metadata created by nebel
//
// ParentAssemblies: assemblies/prometheus/as_prometheus-openshift.adoc
// UserStory: As an Administrator, I want to customize the metrics that Prometheus monitors and collects.

[id='prometheus-metrics']
= Controlling the metrics that Prometheus monitors and collects

By default, Prometheus uses a configuration file ( `https://github.com/fabric8io-images/s2i/blob/master/java/images/rhel/prometheus-config.yml`) that includes all possible metrics exposed by Camel.

If you have custom metrics within your application that you want Prometheus to monitor and collect (for example, the number of orders that your application processes), you can use your own configuration file. Note that the metrics that you can identify are limited to those supplied in JMX.

.Procedure

To use a custom configuration file to expose JMX beans that are not covered by the default Prometheus configuration, follow these steps:

. Create a custom Prometheus configuration file. You can use the contents of the default file (`prometheus-config.yml` https://github.com/fabric8io-images/s2i/blob/master/java/images/rhel/prometheus-config.yml) as a guide for the format. 
+
You can use any name for the custom configuration file, for example: `my-prometheus-config.yml`.

. Add your prometheus configuration file (for example, `my-prometheus-config.yml`) to your application’s `src/main/fabric8-includes` directory.

. Create a `src/main/fabric8/deployment.xml` file within your application and add an entry for the *AB_JMX_EXPORTER_CONFIG* environment variable with its value set to your configuration file. For example:
+
[options="nowrap",subs="attributes+"]
----
spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
            limits:
              cpu: "1.0"
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":1}}}'
          - name: AB_JMX_EXPORTER_CONFIG
            value: "my-prometheus-config.yml"
----
+
This environment variable applies to your application at the pod level.

. Rebuild and deploy your application.
