// Metadata created by nebel
//
// ParentAssemblies: assemblies/prometheus/as_prometheus-extconfig-fuseonline.adoc

[id='prometheus-extconfig-without']
= Configuring a Prometheus instance (without the Prometheus operator)

If you installed an external Prometheus instance without using the Prometheus operator, updating the configuration to monitor {prodnamefuseonline} integration involves editing your Prometheus configuration file and updating the Prometheus pod configuration.

.Prerequisite

You must have write access to the Prometheus configuration file (`prometheus-config.yml`). In the OpenShift web console, the configuration file is located in *Resources* -> *Config Maps*.

.Procedure

. Edit your Prometheus configuration file (`prometheus-config.yml`) as follows:

.. Set the scrape interval to 5 seconds:
+
----
global:
        scrape_interval:     5s
        evaluation_interval: 5s
----

.. Add a scrape config job named `integration-pod` with the Kubernetes service discovery configuration that configures it to scrape pods in the `${OPENSHIFT_PROJECT}`, which is typically the `syndesis` namespace:
+
----
 - job_name: integration-pods

          kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - ${OPENSHIFT_PROJECT}
----

.. Add a `relabel_configs` section that:
* Only scrapes integration pods with the `prometheus.io/scrape` label set to *true*.
* Sets the `__metrics_path__` and `__address__` labels, that are used to scrape the JMX exporter in the integration pod, by using values from the `prometheus.io/path` and `prometheus.io/port` labels.
* Adds pod labels and annotations as Prometheus labels.
* Creates `kubernetes_namespace` and `kubernetes_pod_name` labels.
+
Here is an example `relabel_configs` section:
+
----
relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: labelmap
            regex: __meta_kubernetes_pod_annotation_(syndesis.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
----

.. {prodnamefuseonline} integrations expose a large number of metrics from the JVM, Camel and CXF. To reduce the amount of storage needed for metrics, add the following `metric_relabel_configs` section to filter out metrics that are not displayed in the {prodnamefuseonline} console. 
+
----
 metric_relabel_configs:
          - source_labels: [__name__]
            regex: jmx_(.+)
            action: drop
          - source_labels: [__name__]
            regex: jvm_(.+)
            action: drop
          - source_labels: [__name__]
            regex: process_(.+)
            action: drop
          - source_labels: [type, __name__]
            separator: ':'
            regex: context:(org_apache_camel_ExchangesTotal|org_apache_camel_ExchangesFailed|io_syndesis_camel_StartTimestamp|io_syndesis_camel_LastExchangeCompletedTimestamp|io_syndesis_camel_LastExchangeFailureTimestamp)
            action: keep
----
+
[NOTE]
====
The last configuration line explicitly lists metrics to be added in Prometheus metrics store that are critical to the statistics shown in the {prodnamefuseonline} web console. Your Prometheus instance *must* explicitly allow these metrics to be collected if other metrics are being filtered.
====

. Update the Prometheus pod configuration to store 30 days worth of metric data as follows:
+
----
args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.retention=30d'          
----            
