// Metadata created by nebel
//
// ParentAssemblies: assemblies/prometheus/as_prometheus-fuseonline.adoc

[id='prometheus-fuseonline-apps']
= Monitoring {prodnamefuseonline} integration applications

You can use the Application Monitoring operator to deploy Prometheus so that you can monitor {prodnamefuseonline} integration applications. You can also use Grafana dashboards to visualize the metrics gathered by Prometheus.

.Prerequisites

* You have `cluster admin` access to the OpenShift cluster.

* Deploy Prometheus and Grafana with the Application Monitoring operator by following https://github.com/integr8ly/application-monitoring-operator/blob/master/README.md[these installation instructions]. 

====
[NOTE]

Grafana is a community-supported feature. Deploying Grafana to monitor {integrationprodnamefull} products is not supported with Red Hat production service level agreements (SLAs).

====

.Procedure

. In the {prodnamefuseonline} namespace, set the `monitoring-key=middleware` label by using the following command:
+
----
oc label namespace <fuse-online-namespace> monitoring-key=middleware
----

. Verify that your {prodnamefuseonline} installation added the application monitoring configuration resources to the OpenShift cluster.

.. In the OpenShift web console, go to the `applicaton-monitoring` project and then open the `prometheus-route` URL.
.. In the Prometheus console, go to the *Status* > *Targets* page.
+ 
If a Syndesis target is listed, then {prodnamefuseonline} has been configured for monitoring and you can skip to Step 4.
+
If a Syndesis target is not listed, continue to Step 3.

. If the infrastructure resources are not on the OpenShift cluster:

.. Go to the {prodnamefuseonline} namespace:
+
----
oc project <fuse-online-namespace>
----

.. Install the infrastructure resources by using the following commands:
+
[options="nowrap"]
----

BASEURL=https://raw.githubusercontent.com/syndesisio/syndesis/1.7.x/install/addons

for ADDON in syndesis-integration-dashboard.yml \
  syndesis-integrations-service.yml \
  syndesis-integrations-servicemonitor.yml
do
  oc create -f ${BASEURL}/${ADDON}
done

----
+
====
[NOTE]
The infrastructure resources are not available immediately after you run the install commands. You might need to wait before you can see the {prodnamefuseonline} (Syndesis) targets in the *Prometheus Targets* page.

====

. To access Prometheus:

.. In the OpenShift console for the project where the application monitoring operator is installed, open the list of routes.

.. Next to the *prometheus-route* entry, click the hostname URL to open the Prometheus console.

.. To view a list of the alert rules configured for {prodnamefuseonline} infrastructure components, clicking the *Alerts* menu item.

. To access a Grafana dashboard:

.. In the OpenShift console for the project where the application monitoring operator is installed, open the list of routes.

.. Next to the *grafana-route* entry, click the hostname URL to open the Grafana console.

.. At the top of the Grafana console, click the dashboard selector and then select *Integration - Camel*. 
+
This dashboard displays the standard metrics exposed by Apache Camel integration applications.

